apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test-deployment
  labels:
    app: scale-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-test
  template:
    metadata:
      labels:
        app: scale-test
    spec:
      containers:
      - name: scale-test-app
        image: shestera/scaletestapp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "10Mi"
            cpu: "50m"
          limits:
            memory: "30Mi"
            cpu: "100m"