apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-readonly
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "persistentvolumes", "storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-ops-engineer
  namespace: development
rules:
  - apiGroups: [""]
    resources:
      - "pods"
    verbs: ["create", "delete", "update", "list", "get", "watch"]

  - apiGroups: ["apps"]
    resources:
      - "deployments"
    verbs: ["create", "delete", "update", "list", "get", "watch"]

  - apiGroups: [""]
    resources:
      - "services"
    verbs: ["create", "delete", "update", "list", "get", "watch"]

  - apiGroups: [""]
    resources:
      - "configmaps"
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: security-admin
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]